#export BITGO_TOKEN= # ADD TOKEN FROM test.bitgo.com / bitgo.com
export BITGO_ENVIRONMENT=test
#export BITGO_ENTERPRISE_ID= # ADD ENTERPRISE ID from test.bitgo.com / bitgo.com
export BITGO_ESCROW_ADDRESS=""
export BITGO_UNSPENDABLE_XPUB=xpub661MyMwAqRbcFE3JRXiBw2NCCREosgDdz6GfBTySy2sGhjK4Prd3WMW5LgqFoZC6Pv3vNRbvscyvEgcSDCoqpWELPGBDQr9ZYrGrrhtn3ge # REPLACE OR USE THIS ONE
export MONGODB_URI="mongo/test"
export REDIS_URL="redis:6379"
export NODE_ENV="development"
export PORT=8080
